apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: pihole-etc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: longhorn-ssd
secretGenerator:
  - name: pihole-secrets
    envs:
      - .env
configMapGenerator:
  - name: pihole-custom-hosts
    files:
      - custom.list
