apiVersion: apps/v1
kind: Deployment
metadata:
  name: steel
  namespace: open-webui
  labels:
    app: steel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steel
  template:
    metadata:
      labels:
        app: steel
    spec:
      containers:
        - name: steel
          # pin later
          image: ghcr.io/steel-dev/steel-browser:latest
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 9223
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"
          env:
            - name: DOMAIN
              value: "localhost:3000"
            - name: CDP_DOMAIN
              value: "localhost:9223"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: steel-cache
              mountPath: /app/.cache
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
        - name: steel-cache
          emptyDir: {}
