apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
        - name: lms
          image: lms:latest
          ports:
            - containerPort: 1234
          resources:
            requests:
              memory: "7Gi"
            limits:
              memory: "8Gi"
